[package]
name = "atem-rs"
version = "0.1.0"
edition = "2021"
authors = ["Peter Simonsson <peter.simonsson@gmail.com>"]
license = "MIT OR Apache-2.0"

[dependencies]
bitflags = "2.4.1"
bytes = "1.5"
thiserror = "1.0"
tokio = { version = "1.33", features = ["net", "io-util"] }
tracing = "0.1"

[dev-dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.6", features = ["derive"] }
tokio = { version = "1.33", features = ["net", "io-util", "macros", "rt-multi-thread"] }
tracing-subscriber = "0.3.17"

[[example]]
name = "simple"
